/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};

/* dynamics_p1:(i0[2],i1,i2,i3)->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #3: @2 = 0.1 */
  w2 = 1.0000000000000001e-01;
  /* #4: @3 = 1 */
  w3 = 1.;
  /* #5: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #6: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #7: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #8: @3 = (@3+@4) */
  w3 += w4;
  /* #9: @2 = (@2*@3) */
  w2 *= w3;
  /* #10: @2 = (@2*@0) */
  w2 *= w0;
  /* #11: @1 = (@1-@2) */
  w1 -= w2;
  /* #12: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_p1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dynamics_p1_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_p1_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_p1_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dynamics_p1_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_p1_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dynamics_p1_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_p1_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dynamics_p1_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dynamics_p1_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dynamics_p1_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_p1_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_p1_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_p1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_p1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_p1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_p1_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 5*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
