@echo off
echo Running isort...
isort . --skip .venv --skip venv --skip __pycache__ --skip build --skip dist
echo Running black...
black . --exclude "/(\.venv|venv)/"
echo Running ruff...
ruff check . --fix --exclude .venv,venv,__pycache__,build,dist
echo Running flake8...
flake8 .
echo Running pylint...
pylint trajectolab --ignore=.venv,venv,__pycache__,build,dist
echo Linting complete!
